import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@styles/globals.css';
import Script from 'next/script';
import Footer from '@/components/lib/footer/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full'>
      <Script src='https://cdn.lordicon.com/lordicon.js' />
      <body className={`${inter.className} h-full`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
